import './globals.css'
import { Staatliches } from 'next/font/google'
import { Bowlby_One } from 'next/font/google'


const inter = Staatliches({ subsets: ['latin'], weight: ['400'] })
const bowlby = Bowlby_One({ subsets: ['latin'], weight: ['400'], variable: '--font-bowlby', })

export const metadata = {
	title: 'Agustin Laurito',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<head>
				<script async type="module" src="https://unpkg.com/@splinetool/viewer@0.9.446/build/spline-viewer.js" />
				<meta charSet="UTF-8" />
				<meta name="viewport" content="width=device-width, initial-scale=1.0" />
				<meta name="description" content="Portfolio" />
				<title>Agustin Laurito</title>
				<link rel="icon" href="/favicon.ico" />
				{/* Add any necessary CSS or JavaScript files */}
			</head>
			<body className={`${inter.className} ${bowlby.variable}`}>{children}</body>
		</html>
	)
}
