import './globals.css'
import { Staatliches } from 'next/font/google'
import { Bowlby_One } from 'next/font/google'


const inter = Staatliches({ subsets: ['latin'], weight: ['400'] })
const bowlby = Bowlby_One({ subsets: ['latin'], weight: ['400'], variable: '--font-bowlby', })

export const metadata = {
	title: 'Agustin Laurito',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<head>
				<script async type="module" src="https://unpkg.com/@splinetool/viewer@0.9.446/build/spline-viewer.js" />
				<meta charSet="UTF-8" />
				<meta name="viewport" content="width=device-width, initial-scale=1.0" />
				<title>Agustin Laurito</title>
				<meta name="keywords" content="software developer frontend backend" />
				<meta name="description" content="Hey! I am Agustin, a Software Engineer and a Pilot based in Buenos Aires"/>
				<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
				<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
				<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
				<link rel="manifest" href="/site.webmanifest" />
				<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
				<meta name="msapplication-TileColor" content="#da532c" />
				<meta name="theme-color" content="#ffffff" />
				{/* Add any necessary CSS or JavaScript files */}
			</head>
			<body className={`${inter.className} ${bowlby.variable}`}>{children}</body>
		</html>
	)
}
